### ISSUE TITLE
how to access the taxonomy api

### ISSUE THREAD

**Issue by AndreV84** [eBay/taxonomy-sdk#9]
what level of access is required to get access to the taxonomy API?
with just ebay developer account folks pointed out that response was : "insufficient permissions" while trying to access the api e.g. via curl:
```
curl --location --request GET 'https :// api. ebay. com /commerce/taxonomy/v1/get_default_category_tree_id?marketplace_id=EBAY-US' \
--header 'Authorization: Bearer {{currentAppToken}}' \
--header 'Cookie: {{currentCookie}}'
```

`
{"errors":[{"errorId":1100,"domain":"ACCESS","category":"REQUEST","message":"Access denied","longMessage":"Insufficient permissions to fulfill the request."}]}`

Thanks

**Comment by dvijayan-ebay** [comment]
you can check the allowed oAuth scope 
```
https://developer.ebay.com/api-docs/commerce/taxonomy/resources/category_tree/methods/getCategoryTree 
```
If you have required scope , you can try the API via API tools. 
```
https://developer.ebay.com/my/api_test_tool?index=0&env=production&api=taxonomy&call=get_default_category_tree_id__GET&variation=json 
```

**Comment by AndreV84** [comment]
@dvijayan-ebay 
Thank you for your prompt reply. Seems it worked; However, folks pointed out that it requires to generate 2 hour user token then it expires;
Is there a way without java sdk to use application token with longer validity? 
thanks

**Comment by dvijayan-ebay** [comment]
@AndreV84 I see this API needs App token. 
```
https://api.ebay.com/oauth/api_scope
```
```
https://developer.ebay.com/api-docs/static/oauth-tokens.html
```

**Comment by AndreV84** [comment]
@dvijayan-ebay 
could you clarify please if the taxonomy sdk supports only OAuth tokens with short validity [2 hours]
or also supports Auth'n'Auth tokens with long validity?
if it supports long validity tokens does it also indicate that API http calls could be processed with Auth'n'Auth tokens?
it is not possible to call Taxonomy API calls from ebay python sdk , right?

**Comment by dvijayan-ebay** [comment]
@AndreV84 This API support oAuth App token . Auth n Auth is not supported. 
Can you share me the details about eBay python SDK? Taxonomy API has OpenAPI spec which can help to generate code with base set up ``` https://developer.ebay.com/api-docs/commerce/taxonomy/overview.html ```

**Comment by dvijayan-ebay** [comment]
@AndreV84 Also you can reach to eBay developer community forum which is actively monitored ``` https://community.ebay.com/t5/Developer-Forums/ct-p/developergroup ```
